### ISSUE TITLE
using hasextensions + extensions results in unexpected behavior for DNA data

### ISSUE THREAD

**Issue by sformel-usgs** [iobis/robis#106]
The `hasextensions` and `extensions` arguments don't work together for DNA data, like they do for MOF data. If you use them both for DNA, you are returned an empty data frame.  For MOF, you get the same whether you include both, or just `extensions`.  

I haven't tested this extensively or tried to look into the code, but here are some examples so it can be logged for now.

- DNA, use `extensions` only == expected result
`robis::occurrence(datasetid = "c82dd852-a454-4a5b-8515-ece289f382d3", extensions = "DNADerivedData")`

- DNA, use `extensions` and `hasextensions` == empty result
`robis::occurrence(datasetid = "c82dd852-a454-4a5b-8515-ece289f382d3", hasextensions = "DNADerivedData", extensions = "DNADerivedData")`

- MOF, use `extensions` only == expected result
`robis::occurrence(datasetid = "5e3015f8-a398-46b5-adb1-518a8247aeb9", extensions = "MeasurementOrFact")`

- MOF, use `extensions` and `hasextensions` == expected result
`robis::occurrence(datasetid = "5e3015f8-a398-46b5-adb1-518a8247aeb9", hasextensions = "MeasurementOrFact", extensions = "MeasurementOrFact")`

**Comment by pieterprovoost** [comment]
Thanks @sformel-usgs. This looks like an indexing issue with this specific dataset, not robis related. I'll look into it.

**Comment by pieterprovoost** [comment]
Fixed.

```
> df <- robis::occurrence(datasetid = "c82dd852-a454-4a5b-8515-ece289f382d3", hasextensions = "DNADerivedData", extensions = "DNADerivedData")
Retrieved 38389 records of approximately 38389 (100%)
```
