### ISSUE TITLE
Imports instead of Depends

### ISSUE THREAD

**Issue by sckott** [iobis/robis#11]
you have pkg dependencies as `Depends` in https://github.com/iobis/robis/blob/master/DESCRIPTION#L7-L11 

Best practice in R now is to put pkgs in `Imports` instead, unless you intend to expose functions from pkg dependencies to users of this pkg, which I imagine you dont

**Comment by pieterprovoost** [comment]
I'm having problems with `dplyr`, any thoughts? https://github.com/iobis/robis/blob/master/DESCRIPTION#L9 Thanks.

**Comment by sckott** [comment]
What do you mean?  

also, imported packages need to be listed as imports somewhere in the files in `R/`, I usually list imported packages or imported functions from each package in a single file so they're all in one place -  e.g., like https://github.com/ropensci/gistr/blob/master/R/gistr-package.R#L17-L27

**Comment by pieterprovoost** [comment]
Ok, got it now. The calls to `httr` had `::` but the ones to `dplyr` didn't. I'm going to resort to `@import` for now: 024897b1f29038c69e5a6bfd21ae57776ad68a4f
