### ISSUE TITLE
long WKT strings

### ISSUE THREAD

**Issue by sckott** [iobis/robis#12]
Maybe document for users the option `options(robis_max_characters = xx)` for when WKT strings are not longer than 50,000, for exmaple I had one that is 24,700 characters long, so gave 414 error, since the request used `GET` since here https://github.com/iobis/robis/blob/master/R/occurrence.R#L65 it goes to `GET`

or maybe its documented already somewhere?

**Comment by samuelbosch** [comment]
The robis_max_characters option has been reduced so that it should work for everyone (2048 chars).
