### ISSUE TITLE
Problem with install_github("iobis/robis")

### ISSUE THREAD

**Issue by MilenaLa** [iobis/robis#15]
Hello,
when I try to install a package this is the warning I am getting:

> devtools::install_github("iobis/robis")
> Downloading GitHub repo iobis/robis@master
> from URL https://api.github.com/repos/iobis/robis/zipball/master
> Error in system(full, intern = quiet, ignore.stderr = quiet, ...) : 
>   error in running command
> In addition: Warning message:
> Failed to parse headers:
> X-Geo-Block-List:

Any advice on how to deal with this?

Thanks!

**Comment by pieterprovoost** [comment]
Apologies for the late reply, is this still an issue?

**Comment by MilenaLa** [comment]
Now I apologies for late reply..Y
Yes, this is still an issue.
Best regards,
Milena

**Comment by linslsf** [comment]
I am having the same issue.

**Comment by pieterprovoost** [comment]
Could you please post the output of these commands? Thanks

```R
devtools::session_info()
httr::with_verbose(devtools::install_github("iobis/robis"))
```

**Comment by linslsf** [comment]
> devtools::session_info()
Session info ---------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.1 (2015-06-18)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.893)          
 language (EN)                        
 collate  en_AU.UTF-8                 
 tz       America/Los_Angeles         
 date     2017-05-01                  

Packages -------------------------------------------------------------------------
 package       * version date       source        
 chron           2.3-47  2015-06-24 CRAN (R 3.2.0)
 curl            2.3     2016-11-24 CRAN (R 3.2.5)
 data.table      1.9.6   2015-09-19 CRAN (R 3.2.0)
 devtools      * 1.12.0  2016-06-24 CRAN (R 3.2.5)
 digest          0.6.8   2014-12-31 CRAN (R 3.2.0)
 git2r           0.18.0  2017-01-01 CRAN (R 3.2.5)
 githubinstall * 0.2.1   2016-11-21 CRAN (R 3.2.5)
 httr            1.2.1   2016-07-03 CRAN (R 3.2.5)
 jsonlite        0.9.17  2015-09-06 CRAN (R 3.2.0)
 memoise         1.0.0   2016-01-29 CRAN (R 3.2.3)
 R6              2.1.1   2015-08-19 CRAN (R 3.2.0)
 rstudioapi      0.6     2016-06-27 CRAN (R 3.2.5)
 withr           1.0.2   2016-06-20 CRAN (R 3.2.5)

**Comment by linslsf** [comment]
> httr::with_verbose(devtools::install_github("iobis/robis"))
-> GET /iobis/robis/raw/master/DESCRIPTION HTTP/1.1
-> Host: github.com
-> User-Agent: libcurl/7.51.0 r-curl/2.3 httr/1.2.1
-> Accept-Encoding: gzip, deflate
-> Accept: application/json, text/xml, application/xml, */*
-> 
<- HTTP/1.1 302 Found
<- Date: Mon, 01 May 2017 20:36:39 GMT
<- Content-Type: text/html; charset=utf-8
<- Content-Length: 130
<- Server: GitHub.com
<- Status: 302 Found
<- Cache-Control: no-cache
<- Vary: X-PJAX, Accept-Encoding
<- X-RateLimit-Limit: 100
<- X-RateLimit-Remaining: 100
<- Access-Control-Allow-Origin: https://render.githubusercontent.com
<- Location: https://raw.githubusercontent.com/iobis/robis/master/DESCRIPTION
<- X-UA-Compatible: IE=Edge,chrome=1
<- X-Runtime: 0.039236
<- Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src render.githubusercontent.com; connect-src 'self' uploads.github.com status.github.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com wss://live.github.com; font-src assets-cdn.github.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; img-src 'self' data: assets-cdn.github.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; media-src 'none'; script-src assets-cdn.github.com; style-src 'unsafe-inline' assets-cdn.github.com
<- Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
<- Public-Key-Pins: max-age=5184000; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="RRM1dGqnDFsCJXBTHky16vi1obOlCgFFn/yOhI/y+ho="; pin-sha256="k2v657xBsOVe1PQRwOsHsw3bsGT2VzIqz5K+59sNQws="; pin-sha256="K87oWBWM9UZfyddvDfoxL+8lpNyoUB2ptGtn0fv6G2Q="; pin-sha256="IQBnNBEiFuhj+8x6X8XLgh01V9Ic5/V3IRQLNFFc7v4="; pin-sha256="iie1VXtL7HzAMF+/PVPR9xzT80kQxdZeJ+zduCB3uj0="; pin-sha256="LvRiGEjRqfzurezaWuj8Wie2gyHMrW5Q06LspMnox7A="; includeSubDomains
<- X-Content-Type-Options: nosniff
<- X-Frame-Options: deny
<- X-XSS-Protection: 1; mode=block
<- X-Served-By: f0ee042be143fcba78041fc2f69c0aa7
<- Age: 113
<- Vary: Accept-Encoding
<- X-GitHub-Request-Id: CC45:22675:1350A:1F3AF:59079C57
<- 
-> GET /iobis/robis/master/DESCRIPTION HTTP/1.1
-> Host: raw.githubusercontent.com
-> User-Agent: libcurl/7.51.0 r-curl/2.3 httr/1.2.1
-> Accept-Encoding: gzip, deflate
-> Accept: application/json, text/xml, application/xml, */*
-> 
<- HTTP/1.1 200 OK
<- Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'
<- Strict-Transport-Security: max-age=31536000
<- X-Content-Type-Options: nosniff
<- X-Frame-Options: deny
<- X-XSS-Protection: 1; mode=block
<- ETag: "16958dd82e86a9778d7547a485177fd8f195dda9"
<- Content-Type: text/plain; charset=utf-8
<- Cache-Control: max-age=300
<- X-Geo-Block-List:
<- X-GitHub-Request-Id: 0E88:2316:1F1127F:2053FD1:59079BE6
<- Content-Encoding: gzip
<- Content-Length: 238
<- Accept-Ranges: bytes
<- Date: Mon, 01 May 2017 20:36:39 GMT
<- Via: 1.1 varnish
<- Connection: keep-alive
<- X-Served-By: cache-sea1039-SEA
<- X-Cache: HIT
<- X-Cache-Hits: 1
<- X-Timer: S1493670999.420320,VS0,VE0
<- Vary: Authorization,Accept-Encoding
<- Access-Control-Allow-Origin: *
<- X-Fastly-Request-ID: d98faaa3fb9adf832794b15221b2f1cad5bb21b4
<- Expires: Mon, 01 May 2017 20:41:39 GMT
<- Source-Age: 112
<- 
Downloading GitHub repo iobis/robis@master
from URL https://api.github.com/repos/iobis/robis/zipball/master
-> HEAD /repos/iobis/robis/contents/.gitmodules?ref=master HTTP/1.1
-> Host: api.github.com
-> User-Agent: libcurl/7.51.0 r-curl/2.3 httr/1.2.1
-> Accept-Encoding: gzip, deflate
-> Accept: application/json, text/xml, application/xml, */*
-> 
<- HTTP/1.1 404 Not Found
<- Server: GitHub.com
<- Date: Mon, 01 May 2017 20:36:39 GMT
<- Content-Type: application/json; charset=utf-8
<- Status: 404 Not Found
<- X-RateLimit-Limit: 60
<- X-RateLimit-Remaining: 58
<- X-RateLimit-Reset: 1493674487
<- X-GitHub-Media-Type: github.v3
<- Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
<- Access-Control-Allow-Origin: *
<- Content-Security-Policy: default-src 'none'
<- Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
<- X-Content-Type-Options: nosniff
<- X-Frame-Options: deny
<- X-XSS-Protection: 1; mode=block
<- Content-Encoding: gzip
<- X-GitHub-Request-Id: CC47:4F32:46638A:591306:59079C57
<- 
-> GET /repos/iobis/robis/zipball/master HTTP/1.1
-> Host: api.github.com
-> User-Agent: libcurl/7.51.0 r-curl/2.3 httr/1.2.1
-> Accept-Encoding: gzip, deflate
-> Accept: application/json, text/xml, application/xml, */*
-> 
<- HTTP/1.1 302 Found
<- Server: GitHub.com
<- Date: Mon, 01 May 2017 20:36:39 GMT
<- Content-Type: text/html;charset=utf-8
<- Content-Length: 0
<- Status: 302 Found
<- X-RateLimit-Limit: 60
<- X-RateLimit-Remaining: 58
<- X-RateLimit-Reset: 1493674487
<- Cache-Control: public, must-revalidate, max-age=0
<- Expires: Mon, 01 May 2017 20:36:39 GMT
<- Location: https://codeload.github.com/iobis/robis/legacy.zip/master
<- Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
<- Access-Control-Allow-Origin: *
<- Content-Security-Policy: default-src 'none'
<- Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
<- X-Content-Type-Options: nosniff
<- X-Frame-Options: deny
<- X-XSS-Protection: 1; mode=block
<- Vary: Accept-Encoding
<- X-Served-By: e14705a23c085afeff5e104b1fc3922a
<- X-GitHub-Request-Id: CC47:4F32:4663A3:59132E:59079C57
<- 
-> GET /iobis/robis/legacy.zip/master HTTP/1.1
-> Host: codeload.github.com
-> User-Agent: libcurl/7.51.0 r-curl/2.3 httr/1.2.1
-> Accept-Encoding: gzip, deflate
-> Accept: application/json, text/xml, application/xml, */*
-> 
<- HTTP/1.1 200 OK
<- Content-Length: 15976
<- Access-Control-Allow-Origin: https://render.githubusercontent.com
<- Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'
<- Strict-Transport-Security: max-age=31536000
<- Vary: Authorization,Accept-Encoding
<- X-Content-Type-Options: nosniff
<- X-Frame-Options: deny
<- X-XSS-Protection: 1; mode=block
<- ETag: "df9d532f0c5adfbe283091d34a1dc0ea28adcd7d"
<- Content-Type: application/zip
<- Content-Disposition: attachment; filename=iobis-robis-df9d532.zip
<- X-Geo-Block-List: 
<- Date: Mon, 01 May 2017 20:36:40 GMT
<- X-GitHub-Request-Id: CC49:233A:18A3AD:1EDC65:59079C58
<- 
Installing robis
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Warning in download.packages(x$name, destdir = dest_dir, repos = x$repos,  :
  download of package ‘dplyr’ failed
Error in download.packages(x$name, destdir = dest_dir, repos = x$repos,  : 
  subscript out of bounds
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  download had nonzero exit status

**Comment by pieterprovoost** [comment]
@linslsf This is probably not related to the problem reported by @MilenaLa, but can you please update R (run `devtools::session_info()` to confirm the update) and try again?
