### ISSUE TITLE
Subscript out of bounds error when taxon not found

### ISSUE THREAD

**Issue by sarahfaulwetter** [iobis/robis#22]
When AphiaID or taxon is not found, script breaks with an error  and warnings

`occ <- occurrence("Vigtorniella zaikai", fields = c("decimalLongitude", "decimalLatitude"))`

gives

`Error in value[[jvseq[[jjj]]]] : subscript out of bounds
In addition: Warning messages:
1: In occurrence("Vigtorniella zaikai", fields = c("decimalLongitude",  :
  Taxon Vigtorniella zaikai not found
2: In occurrence("Vigtorniella zaikai", fields = c("decimalLongitude",  :
  Following fields where not found and initialized to NA: decimalLongitude, decimalLatitude`

Same with aphiaID not found: 
`occ <- occurrence(aphiaid=129828, fields = c("decimalLongitude", "decimalLatitude"))`

gives

`Error in value[[jvseq[[jjj]]]] : subscript out of bounds
In addition: Warning messages:
1: In occurrence(aphiaid = 129828, fields = c("decimalLongitude", "decimalLatitude")) :
  AphiaID 129828 not found
2: In occurrence(aphiaid = 129828, fields = c("decimalLongitude", "decimalLatitude")) :
  Following fields where not found and initialized to NA: decimalLongitude, decimalLatitude`

While these can be caught with `try` it would probably be more convenient to return an empty dataframe.

**Comment by pieterprovoost** [comment]
Fixed, thanks for reporting!

https://github.com/iobis/robis/commit/de5d484ff3bb731a5960af92eda7b272fdb2d5f7
