### ISSUE TITLE
occurrence: full field list option

### ISSUE THREAD

**Issue by ekleins** [iobis/robis#25]
When occurrence(spp), a data frame with only fields with data are included. You can specify the fields you want in the output, but if you want all the fields you have to specify all explicitly. 

An option like "allfields = TRUE" (FALSE by default, and overriding "fields" when TRUE) could be useful, retuning NA values in the empty fields.

**Comment by samuelbosch** [comment]
Personally, as an R user I would even make this the default behavior, in this way you always get the same dataframe regardless of the provided species.
This could be implemented without an additional parameter. 

Proposal:
- create a new documented object with the list of supported fields, and refer to it in the occurrence function
- when NULL is passed to the fields parameter: use the current behavior
- when 'all' is passed to the fields parameter: return all fields
- make fields='all' the default

Feel free to disagree :-)

**Comment by pieterprovoost** [comment]
I'm not in favour of making this the default behaviour. There are 169 terms in the occurrence core, without counting extensions terms and fields added by OBIS. This will create a lot of clutter.

I can see the merit for an option like this, but I think for most users it will be a huge annoyance if they have to scroll through endless empty columns.

**Comment by pieterprovoost** [comment]
Closing this for now. Please note that a `field` parameter has been added to restrict the returned set of fields.
