### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/robis#29]
Installation on Windows systems sometimes fails with `there is no package called 'DBI'` and similar messages. This seems to be related to https://github.com/hadley/devtools/issues/1298

**Comment by samuelbosch** [comment]
Issue should be fixed in devtools 1.13.0 (May 2017 on CRAN). See e.g. [hadley/devtools/#1330](https://github.com/hadley/devtools/issues/1330)

**Comment by samuelbosch** [comment]
I tried setting up automated Windows testing on AppVeyor but R is not very well supported apparently as I had the following issue that I found no fix for:

Project file "robis.Rproj" is not a valid MSBuild project file which must be an XML.
