### ISSUE TITLE
empty rows when requesting checklist

### ISSUE THREAD

**Issue by ekleins** [iobis/robis#30]
the `checklist` function from a specified geometry is returning rows with only NAs. Is it a problem of the function or there are empty records in the DB for the geometry?.

The geometry: 
```
polygon = "POLYGON ((-77.87109 37.50973, -76.15723 40.48038, -73.78418 42.00033, -72.07031 42.61779, -70.40039 42.55308, -69.38965 42.13082, -68.73047 41.34382, -68.15918 40.01079, -71.14746 39.70719, -71.85059 39.26628, -73.12500 38.44498, -73.69629 37.89220, -74.44336 36.84446, -74.61914 35.71084, -74.66309 35.46067, -75.54199 35.71084, -78.17871 36.06686, -77.87109 37.50973))"
```

The request: 
```
taxa = checklist(geometry = polygon)
```

the empty records in _taxa_ are:
```
which(is.na(taxa$id))
[1] 1451 7856 7882 7926 8028 8046 8212
```

Saludos, EKS

**Comment by pieterprovoost** [comment]
Thanks for reporting. This was fixed at the database level, you should now see some orphaned taxa where the empty records used to be.
