### ISSUE TITLE
Error: get_wormsid produces missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by miriamgrace** [iobis/robis#34]
Hi, I'm not sure if this is the right place to post errors, so sorry if not. I'm running a query to get WoRMS ID corrsponding to scientific names of various species in OBIS, but I get the following error for some species:

`Error in if (els[1] != "SOAP" && els[1] != "SOAP-ENV") code <- NULL else code <- els[2] : missing value where TRUE/FALSE needed`

The basic query is:

```
ukeez_aphia <- get_wormsid(searchterm = ukeez_names, accepted = TRUE,ask=FALSE, verbose=FALSE)
```

I can add more code if needed. Thanks for any suggestions!

**Comment by pieterprovoost** [comment]
Hi Miriam, this issue seems to be related to the `taxize` or `taxizesoap` package, so please create in issue in https://github.com/ropensci/taxize or https://github.com/ropensci/taxizesoap. Thanks!
