### ISSUE TITLE
occurrence with areaid not working

### ISSUE THREAD

**Issue by ekleins** [iobis/robis#35]
I've tried occurrence `("Pterois volitans", areaid=253)` and I never got a result, hangs forever... It supposed to be 484 records resulting from that query

It is working OK in the robis2 package.

**Comment by pieterprovoost** [comment]
Seems to be ok now, please let me know if the problem persists. This should not happen anymore once we move to robis2.

```
> data <- occurrence("Pterois volitans", areaid=253)
Retrieved 484 records of 484 (100%)
```
