### ISSUE TITLE
robis citation

### ISSUE THREAD

**Issue by wardappeltans** [iobis/robis#39]
update info for citation("robis")

**Comment by samuelbosch** [comment]
The current citation is:

Pieter Provoost and Samuel Bosch (NA). robis: R client for the OBIS API. R package version 0.2.0.

What would you like it to look like?

**Comment by samuelbosch** [comment]
Warning messages:
1: In citation("robis") :
  no date field in DESCRIPTION file of package 'robis'
2: In citation("robis") :
  could not determine year for 'robis' from package DESCRIPTION file

**Comment by samuelbosch** [comment]
Fixed in 0.0.4
