### ISSUE TITLE
different number of records robis vs Elasticsearch

### ISSUE THREAD

**Issue by wardappeltans** [iobis/robis#40]
3125 records: occurrence("Cetacea", geometry = "POLYGON ((-55.000 -37.000, -55.000 -58.000, -70.000 -58.000, -70.000 -37.000,-55.000 -37.000))")

3131 records: http://download.iobis.org/?scientificname=Cetacea&geometry=POLYGON%20((-55.000%20-37.000,%20-55.000%20-58.000,%20-70.000%20-58.000,%20-70.000%20-37.000,-55.000%20-37.000))

**Comment by pieterprovoost** [comment]
These 6 records are located right on the edges of the bounding box. We can get a higher precision by [tweaking the number of geohash tree levels](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-shape.html) but that will likely impact performance.

```R
library(robis)
library(dplyr)

down <- read.csv("d6b711427badc23d94b849ec02ddb65e9fad662c.csv")
cet <- occurrence("Cetacea", geometry = "POLYGON ((-55.000 -37.000, -55.000 -58.000, -70.000 -58.000, -70.000 -37.000,-55.000 -37.000))")

diff <- down %>% filter(!id %in% cet$id)
leafletmap(diff)
```

![screen shot 2017-11-03 at 13 43 07](https://user-images.githubusercontent.com/490041/32374195-f66ff594-c09c-11e7-98b5-0a2107fdf39f.png)
