### ISSUE TITLE
progress indicator formatting issue

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/robis#42]
```R
> dor <- occurrence("Doridoidea")
Retrieved  records of 14000 (%)0 (100%)
```

**Comment by samuelbosch** [comment]
Cause: service returns lastpage=false while it is in fact the last page (http://api.iobis.org/occurrence?scientificname=Doridoidea&skipid=724920773)
When you take the last id from that page you get no results anymore: http://api.iobis.org/occurrence?scientificname=Doridoidea&skipid=739118594

Fixed the formatting in robis but ideally the webservice should be fixed as well, althoug it is a very minor issue that will probably occur for species with a number of records which are multiple of 2000 and more than 2000.
