### ISSUE TITLE
Specify fields in occurrence() in robis2.0.x?

### ISSUE THREAD

**Issue by tomjwebb** [iobis/robis#49]
Am I missing something or is there no longer an option in `occurrence` to specify the fields to return?

Also have some of the field names changed? For instance, there is no longer `depth` but rather two fields, `minimumDepthInMeters`, `maximumDepthInMeters`?

For ref, I ran this query:
```{r}
library(tidyverse)
library(raster)
library(robis)
library(mregions)
uk <- extent(c(-16, 4, 45, 65))
uk_poly <- as(as(uk, "SpatialPolygons"), "SpatialPolygonsDataFrame")
cal_fin <- occurrence(scientificname = "Calanus finmarchicus",
                      geometry = mr_as_wkt(uk_poly)) %>%
  as_tibble()
```

**Comment by pieterprovoost** [comment]
`fields` has been added in v2.1.2.

**Comment by pieterprovoost** [comment]
The package now adds `depth` as a polyfill as long as the API does not return `depth`.
