### ISSUE TITLE
Server error for large queries

### ISSUE THREAD

**Issue by ahjones1** [iobis/robis#6]
Receive a server error when running large queries through the OBIS client. Is this related to the internet connection or something on the server end?
```
Crustacea <- occurrence(scientificname = "Crustacea")

Retrieved 22000 records of 7303481 (0%)
Error in occurrence(scientificname = "Crustacea") : 
  server error: (504) Gateway Timeout
```

**Comment by pieterprovoost** [comment]
Timeouts should no longer happen, but improvements will need to be made to the API in order to have acceptable performance for large queries.
