### ISSUE TITLE
rOBIS does not responsd on extractign data using SPOCC for large data

### ISSUE THREAD

**Issue by haniehsaeedi** [iobis/robis#75]
Hi Pieter, I am trying to extract the data from rOBIS and GBIF using Spocc package, when I increase the limit to more than 100,000 data rOBIS does not respond. I copy here my code and my error message. Do you know what causes this?
library("spocc")
out <- occ(query = c('Mollusca'), obisopts = list(areaid = 31914, startdepth = 200, enddepth = 6000), gbifopts=list(hasCoordinate=TRUE, depth='200,6000', waterBody = "South Atlantic Ocean"), from = c('gbif','obis'),limit = 14673)
dat <- occ2df(out)
Warning message:
In foo_obis(sources, x, y, s, z, hc, d, w, ds$obis) :
  No records returned in OBIS for Mollusca

**Comment by pieterprovoost** [comment]
@haniehsaeedi Can you please open an issue at https://github.com/ropensci/spocc? spocc does not robis but connects directly to the OBIS API. The same query works fine with robis:

```r
> df <- robis::occurrence("Mollusca", areaid = 31914, startdepth = 200, enddepth = 6000)
Retrieved 13207 records of approximately 13207 (100%)
```

**Comment by haniehsaeedi** [comment]
@pieterprovoost 
Thanks, Pieter, I opened an issue at https://github.com/ropensci/spocc
Yes directly from robis works perfectly, but with Spocc the high limitations crash somehow.

**Comment by haniehsaeedi** [comment]
@pieterprovoost 
Is it possible to extract data from rOBIS for multiple taxa, let say if I want to extract for Mollusca and Ispoda
df <- robis::occurrence("Mollusca", "Isopoda", areaid = 31914, startdepth = 200, enddepth = 6000) gives error

**Comment by haniehsaeedi** [comment]
I fixed it, this works
df <- robis::occurrence(c("Mollusca", "Isopoda"), areaid = 31914, startdepth = 200, enddepth = 6000)
