### ISSUE TITLE
robis is archived on CRAN

### ISSUE THREAD

**Issue by fmichonneau** [iobis/robis#76]
Hello,

I noticed that `robis` is now archived on CRAN: https://cran.r-project.org/web/packages/robis/index.html

Do you have plans/a timeline to submit it again there?

Thanks!

**Comment by pieterprovoost** [comment]
@fmichonneau Version 2.7.2 has just been submitted to CRAN and is awaiting review.

**Comment by fmichonneau** [comment]
great, thank you!

**Comment by pieterprovoost** [comment]
Version 2.8.1 is now on CRAN: https://cran.r-project.org/web/packages/robis/index.html
