### ISSUE TITLE
Occurrence(taxonid = [number]) pulls down subspecies too

### ISSUE THREAD

**Issue by goldsoundz80** [iobis/robis#96]
When pulling records by taxonID (WoRMs AphiaID), Obis returns the records associated with that ID, as well as any subspecies that are attached to it.

You can recreate this with this code:
`df <- occurrence(taxonid = 555677)`

Now look at the data frame and you'll see it contains records for both 555677 and 555679 (dplyr required for this bit):
`df_result <- df %>% 
  group_by(aphiaID) %>% 
  summarise()`

Is there any way to tell robis to exclude subspecies (or child records, or whatever they're called)? I am trying to match max / min depth to a list of aphiaID's I already have so I don't want the extras!

**Comment by pieterprovoost** [comment]
This is by design, queries for higher level taxa will always return lower level taxa (this also goes for genus, family, etc). There's nothing in robis, but if you only want species level identifications you could filter on `speciesid == aphiaID`. `speciesid` is a field added by OBIS that contains the AphiaID of the (accepted) species name linked to the record.

```r
> df %>% group_by(aphiaID, speciesid) %>% summarise(n())
# A tibble: 2 × 3
# Groups:   aphiaID [2]
  aphiaID speciesid `n()`
    <int>     <int> <int>
1  555677    555677  1354
2  555679    555677     2

> df %>% filter(speciesid == aphiaID) %>% group_by(aphiaID, speciesid) %>% summarise(n())
# A tibble: 1 × 3
# Groups:   aphiaID [1]
  aphiaID speciesid `n()`
    <int>     <int> <int>
1  555677    555677  1354
```

**Comment by goldsoundz80** [comment]
This is super helpful. It took me ages to figure out what it was doing with my data because I could only see species/subspecies examples, but it makes much more sense now I realise it would do this for other taxonomic levels. Thank you for getting back to me so quick!
