### ISSUE TITLE
OBIS API returns error when using multi polygon geometry

### ISSUE THREAD

**Issue by goldsoundz80** [iobis/robis#97]
I would like to filter results by species occurrence in the UK EEZ.

I use mregions to grab the shape file:
`uk_eez <- mregions::mr_shp(key = "MarineRegions:eez",
                           filter = "United Kingdom Exclusive Economic Zone"
                           )`
I simplify the shape file with rmapshaper and make it a spatial dataframe:
`uk_eez_simple <- sf::as_Spatial(rmapshaper::ms_simplify(uk_eez)`

Then run my robis script, using mregions to create a wkt:
`whale <- robis::occurrence(scientificname = "Megaptera novaeangliae", geometry = mregions::mr_as_wkt(uk_eez))`

It returns an error:

> Error: The OBIS API was not able to process your request. If the problem persists, please contact helpdesk@obis.org.

The example in the robis vignette works correctly:
`occurrence("Abra alba", geometry = "POLYGON ((2.59689 51.16772, 2.62436 51.14059, 2.76066 51.19225, 2.73216 51.20946, 2.59689 51.16772))")`

If I use my first script to instead download the "Samoan Exclusive Economic Zone" shape file instead of the UK, it works. Norway does not work. This led me to thinking that it's a problem with multi polygons, since the Samoan EEZ is a single polygon (the UK and Norway have lots of islands and are multi polygons).

I created a shape file in qGIS that's a single polygon over the UK, and it works, returning results from Obis correctly.

Any assistance would be much appreciated, thanks! Rob

**Comment by pieterprovoost** [comment]
Thanks Rob. I noticed that you are not passing your simplified geometry to `mregions::mr_as_wkt` but rather the original one. But if you set `verbose = TRUE` on `occurrence()` you will see that it returns `414 URI Too Long`, even with the simplified version. The WKT string is sent as part of the URL so it cannot be very long. So there are two options: either make the WKT shorter by using more aggressive simplification and maybe less digits, or fetch the data for a bounding box and do the further filtering in R. Here's an example of both approaches, the second one is probably best as it is more accurate:

```r
library(dplyr)

# Simplification approach

uk_eez <- mregions::mr_shp(key = "MarineRegions:eez", filter = "United Kingdom Exclusive Economic Zone" )
uk_eez_simple <- sf::st_simplify(uk_eez, dTolerance = 10000)
wkt <- sf::st_as_text(uk_eez_simple$geometry, digits = 3)
whale <- robis::occurrence(scientificname = "Megaptera novaeangliae", geometry = wkt)

# Bounding box approach

bbox <- sf::st_as_sfc(sf::st_bbox(uk_eez))
bbox_wkt <- sf::st_as_text(bbox)
whale_bbox <- robis::occurrence(scientificname = "Megaptera novaeangliae", geometry = bbox_wkt)
whale <- whale_bbox %>%
  sf::st_as_sf(coords = c("decimalLongitude", "decimalLatitude"), crs = 4326) %>%
  filter(sf::st_intersects(geometry, uk_eez, sparse = FALSE))
```

**Comment by goldsoundz80** [comment]
This is incredibly helpful, thank you! It makes much more sense now I realise it's talking to the API with a URL, which has a character limit of 2048! The problem has been that whatever I get wrong in my script, it returns the same API error and doesn't lead me to the cause of the problem, but I guess you can't get around this with the way the API works. I was not aware of the bounding box approach – that seems like the way to go since I can filter with occurrence() to make sure data aren't on land.

> Thanks Rob. I noticed that you are not passing your simplified geometry to mregions::mr_as_wkt but rather the original one.
Apologies, that was just a mistake when I typed it out for posting here :) 

Thanks again, I've been tearing my hair out over this one. Have a great weekend!
